### ISSUE TITLE
[BUG] Sentence cutting inside component

### ISSUE THREAD

**Issue by nborie** [PremierLangage/platon-front#16]
At least for the component CheckBox Group, long clickable texts are cut properly... This is a very minor bug but on the way to perfect features.

![component_cut](https://user-images.githubusercontent.com/6042616/73911063-53c43400-48b1-11ea-86c4-0c7fde46b926.png)

On this piece of screenshot, we can see the too long item going away in the nothingness.

**Comment by mciissee** [comment]
tracked in #41 #53
