### ISSUE TITLE
Strange echo when using dead keys

### ISSUE THREAD

**Issue by niotie** [PremierLangage/platon-front#2]
When typing accents in the editor on my mac, the editor's behaviour is strange. For exemple, typing the backquote (`) then space prints two backquotes.

Other examples :
- '´' followed by 'E' prints 'ÉÉ'
- '^' twice followed by a space prints '^^^^', etc. 

I understand that one may want the typing of (`) to automatically insert a closing backquote, but in that case the cursor should be placed in-between, not after the closing one.

**Comment by mciissee** [comment]
Fixed in the next version that will be released

https://premierlangage.github.io/platon-front/components/forms/wc-code-editor
