### ISSUE TITLE
[ENHANCEMENT] DragDrop behavior

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/platon-front#26]
@mciissee 

Avec @esandier, nous ne sommes pas parfaitement satisfaits du comportement actuel du composant DragDrop.

Voilà ce qu'on voudrait.

1. Possibilité d'avoir des groupes de DragDrop indépendants : les étiquettes de l'un ne peuvent pas être déposées sur les étiquettes de l'autre.
2. Un comportement un peu plus "précis" (distinction entre les étiquettes et les zones de drop, possibilité d'avoir des étiquettes à usage unique, etc.).
3. Un comportement supplémentaire et analogue au drag and drop à base de clics (clic sur la source puis clic sur la cible).

Voilà ce qu'on propose.

Les composants DragDrop auraient les propriétés suivantes.
* `groupId`
* `type` : `label` ou `drop`
* `cloneable` pour les dragdrops de type `label`
* `origin`

Le nouveau comportement serait le suivant.
  * si le composant-cible n'est pas un `drop` avec le même `groupId` que le composant-source, on ne fait rien ;
  * sinon,
    * si le composant-source est un label `cloneable`, on copie le `content` du composant-source dans le `content` du composant-cible ;
    * si le composant-source est un label non `cloneable`, on renvoie le `content` du composant-cible dans le composant dont l'id est dans `origin` (si `origin` n'est pas vide), on copie le `content` et l'`origin` du composant-source dans le composant-cible, on vide le `content` du composant-source ;
    * si le composant-source est un `drop`, on échange le content et l'origine entre les deux composants.

On a conscience que ce genre de modifs va entraîner des problèmes de rétro-compatibilité mais le composant DragDrop n'est pas encore énormément utilisé et ça nous semble globalement le bon comportement à avoir pour un DragDrop.

**Comment by mciissee** [comment]
tracked in #43
