### ISSUE TITLE
[ENHANCEMENT] Automaton editor 100% web responsive

### ISSUE THREAD

**Issue by nborie** [PremierLangage/platon-front#27]
Currently, at least two people (DR and NB) did manage to build an automaton on smartphones this 21 April 2020.

Working actions are :
* create node (double touch in free space)
* move nodes (single finger slide on middle of a node and slice)
* create transition (single finger slide from node corner to another or itself)
* transition selection (single finger on the label)
* change transition labels (button transition change)

We just didn't manage to select a node. On computer, this enable the buttons (initial, final, etc...). Perhaps this can be solve just by enabling this menu when moving the node ?

Thanks for this already great feature anyway...

**Comment by mciissee** [comment]
duplicated in #39
