### ISSUE TITLE
[ENHANCEMENT] Allow inline `css` in the property `css` of components

### ISSUE THREAD

**Issue by esandier** [PremierLangage/platon-front#28]
**Related Component**
Every component

**Feature Description**
It should be possible to set `css` properties of a component.

**Use Case**
```dragdrop.set_property("width", "4em")```

**Comment by mciissee** [comment]
Vous pouvez tester cette feature avec les composants à l'adresse suivante:

https://premierlangage.github.io/platon-front/components

La syntaxe est la suivante:

```
class1 class2 class3 <> width: 50px; color: red;
```

Le séparateur `<>`est obligatoire si vous mettez des classes et des styles, le `;` est obligatoire pour les styles
