### ISSUE TITLE
[ENHANCEMENT] freeze image built with component viewer

### ISSUE THREAD

**Issue by nborie** [PremierLangage/platon-front#29]
I would like that the component GraphDrawer (or Graph Viewer) allows to freeze the size of the generated image (from DOT).

Currently a mouse scroll when the pointer is over the image make a zoom/unzoom of the image and produces some moves of the image. I am convinced that this can be a feature in some contexts so I am not asking to freeze every times. A good solution seems to me proposing a new boolean attribute inside the components enabling the freeze.

I currently test with this : https://pl.u-pem.fr/filebrowser/demo/17666/

**Comment by mciissee** [comment]
tracked in #44
