### ISSUE TITLE
[ENHANCEMENT] TextSelect : more flexible splitting

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/platon-front#31]
@nimdanor @esandier

**Related Component**
TextSelect

**Feature Description**
Actuellement, c'est le composant TextSelect qui découpe le texte qui lui est fourni (dans la propriété `text`) en unités cliquables. Tout ce qu'on peut choisir ce sont les séparateurs utilisés pour le découpage (propriété `separator`).

Je propose de changer la sémantique de la propriété `text` de façon à y inclure le découpage du texte (par des accolades par exemple) et permettre, de ce fait, un découpage plus flexible.

```
{Ô} {rage} ! {Ô} {désespoir} ! {Ô} {vieillesse} {ennemie} ! <br>
{N'}{ai}-{je} {donc} {tant} {vécu} {que} {pour} {cette} {infamie} ?
```

**Use Case**
La nouvelle sémantique permettrait de traiter les cas suivants:
* Cas ambigus de découpage des textes : "peux-tu" c'est deux mots, mais "cerf-volant" c'est un seul mot.
* Textes avec une mis en forme : texte versifié, texte à plusieurs paragraphes.
* Unités cliquables différentes des mots (groupes de mots ou phrases complètes par exemple).

**Additional Info**
* Voir PremierLangage/components#26 pour une discussion sur la même question.
* Du point de vue Angular, il y a juste un petit bout de JS à a changer :
```
<script>
var index = -1;
string = string.replace(/\{([^\{\}]*)\}/g, function(match, p) {
  index++;
  return `<span data-index="${index}"> ${p} </span>`;
});
</script>
```
* La propriété `separator` devient inutile.
* Bien entendu, pour garder une facilité d'usage pour l'utilisateur, il faudra ajouter des méthodes qui permettent une "mise en accolades" automatique d'un text brut dans les cas courants.
* De toute façon, fournir le texte d'une part et les positions des mots solutions d'autre part, c'était déjà pas pratique. Le prof, ce dont il a envie, naturellement, c'est de fournir juste le texte avec les mots solutions "marqués". Donc, il y aurait de toute façon du traitement du texte à faire avant de l'envoyer au composant.

**Comment by mciissee** [comment]
tracked in #55
