### ISSUE TITLE
[ENHANCEMENT] List Input

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/platon-front#34]
**Name and Html Selector**
selector c-listInput (may by c-list-compsant if you make a recursive structure)

**Goal of the Component**
Possibility to enter a list of values (str or int).
With a plus sign button to add a new input zone.

**Properties of the Component**
If the empty list is ok or not.
if "mixted" value type is ok or else "int" or "str" 
if the text is of "control input type" the list of "valid" texts. 

sortedeval boolean

**Example**
Exercice: give a list of Design patterns names you see in this diagram.

**Dependencies**

**Additional Info**
the eval function must compare by able to compare sorted and unsorted versions of the solution and the answer.

**Comment by mciissee** [comment]
tracked in #47
