### ISSUE TITLE
[ENHANCEMENT] Python classes for Radio and Checkbox

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/platon-front#37]
With @esandier, we have written some Python methods to makes easier the use of Radio and Checkbox components.

Here are our production :
/utils/components/checkbox.py
/utils/components/radio.py

@mciissee : Does it seem ok to you to include these methods in the standard Python class of Radio and Checkbox ?

**Comment by mciissee** [comment]
Yes these methods will be added to the specified components.

**Comment by mciissee** [comment]
tracked in #41
