### ISSUE TITLE
[WEBCOMPONENT] CheckboxGroup

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/platon-front#41]
**Selector**
wc-checkbox-group

**Goal**
CheckboxGroup can be used to let the user know they need to make a binary decision.

**Properties (excluding the default properties cid, selector, debug...)**

| property | description |
|----------|------------|
|`disabled: boolean` | disable interaction with the component |
|`items: CheckboxGroupItem[]` | An array of objects of the following format representing the items to render.|

`CheckboxGoupItem` format:

```javascript
{
    "id": string, // id of the item (required).
    "content": string, //  HTML, markdown, MathJax or text content of the item.
    "css": string, // optional css classes of the item separated by a space.
    "checked": boolean, // optional value indicating whether the item is checked (false if not specified).
}
```

**Controller**
see #37 

**Dependencies**
Optional list of javascript or python (for grader) libraries used by the component.

**Example**
[https://pl.u-pem.fr/components/checkbox-group](https://pl.u-pem.fr/components/checkbox-group)

**Additional Info**
Add any other context, schemas or screenshots about the component request here.

**Comment by mciissee** [comment]
https://premierlangage.github.io/platon-front/components/widgets/wc-checkbox-group

**Comment by nimdanor** [comment]
![image](https://user-images.githubusercontent.com/10084549/96142927-e4541900-0f02-11eb-922f-fe26f9b7010f.png)

le 'Choix 1' n'apparait pas dans le composant.

**Comment by nimdanor** [comment]
Maintenant cela marche ....
