### ISSUE TITLE
[WEBCOMPONENT] MatchList

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/platon-front#49]
**Selector**
wc-match-list

**Goal**
Match list lets users connect items between two lists

***Features***:
- dragdrop
- click to connect
- responsive #17 .

**Properties (excluding the default properties cid, selector, debug...)**

see [https://pl.u-pem.fr/components/match-list](https://pl.u-pem.fr/components/match-list)

**Controller**
An optional python class attached to the component instance.

**Dependencies**
Optional list of javascript or python (for grader) libraries used by the component.

[jsplumb](https://www.npmjs.com/package/jsplumb)

**Example**
Optional link to an exercise that reproduce the behavior of the component.

**Additional Info**
Add any other context, schemas or screenshots about the component request here.

**Comment by mciissee** [comment]
https://premierlangage.github.io/platon-front/components/forms/wc-match-list

**Comment by nimdanor** [comment]
est il possible d'associer plusieurs sources a une même target je n'ai pas trouver d'option pour le faire ?
cela serait pourtant utile. 
L'ancien Matchlist permet il de le faire ?

**Comment by mciissee** [comment]
Il faut cliquer sur les 2 noeuds que vous voulez connecter si une source est déjà présente sur la target

**Comment by nimdanor** [comment]
Donc le drag and drop ne fonctionne que pour le premier lien.
