### ISSUE TITLE
[WEBCOMPONENT] Matrix

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/platon-front#51]
**Selector**
wc-matrix

**Goal**
Matrix provides a way for users to enter a matrix of data.

**Properties (excluding the default properties cid, selector, debug...)**

| property | description |
|----------|------------|
| `matrix: MatrixCell[][]` |  A 2D array of MatrixCell objects |
| `resizable: boolean` | A value indicating whether the matrix is resizable |

A `MatrixCell`  is an object representing the properties of [InputBox](#46 )

**Controller**
An optional python class attached to the component instance.

**Dependencies**
Optional list of javascript or python (for grader) libraries used by the component.

**Example**
[https://pl.u-pem.fr/components/math-matrix](https://pl.u-pem.fr/components/math-matrix)

**Additional Info**
Add any other context, schemas or screenshots about the component request here.

**Comment by nborie** [comment]
I do not know how much these could need several component and not a single one ; I think these are two kind of use of a matrix as a form :

* All coefficient are possible inputs (the current state of the components) (a grid of input numbers)
* All coefficient are stetted immutably in the exercise but can be selected (a grid of boolean selected or not)

For example, in this exercise : [rank of an easy matrix](https://pl.u-pem.fr/filebrowser/demo/21976/) , the student has just to fill a single integer which is the rank. A nicer exercise could be : "Please select a set of pivots which could transform this matrix into a triangular one up to permutation of its columns" For that, a matrix form with just selected or not could be a nice component.

Another use of the second form is also "learn to echelonize step by step" which could be a very very interesting exercise. This last one can also be declined in learn to build Normal Smith Form in principal ideal domain, etc....

**Comment by mciissee** [comment]
https://premierlangage.github.io/platon-front/components/forms/wc-matrix
