### ISSUE TITLE
[WEBCOMPONENT] TextSelect

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/platon-front#55]
**Selector**
wc-text-select

**Goal**

Provides a way to select a part of a text.
Selections of chars, of words, of phrases.
Verification by index or by value.
An exercice to create a text-select exercice is a good idea.

**Properties (excluding the default properties cid, selector, debug...)**

see [https://pl.u-pem.fr/components/text-select](https://pl.u-pem.fr/components/text-select)

**Controller**
An optional python class attached to the component instance.

**Dependencies**
Optional list of javascript or python (for grader) libraries used by the component.

**Example**

[https://pl.u-pem.fr/components/text-select](https://pl.u-pem.fr/components/text-select)
[projet Rousseau clone](https://pl.u-pem.fr/filebrowser/demo/21974/)

**Additional Info**
Add any other context, schemas or screenshots about the component request here.

**Comment by ddoyen** [comment]
Je pense toujours qu'il y a un changement fondamental à faire dans le fonctionnement de ce composant (ce qui ne pose pas de problème de rétrocompatiblité puisque personne ne l'utilise réellement pour l'instant).

Voir #31

@nborie @nimdanor @esandier Quel est votre avis sur ce sujet ?

**Comment by nimdanor** [comment]
Que propose tu ?? 
je suis d'accord pour discuter ;)


Il faut pouvoir initialiser le text de façon simple:
textaselctionner="qkfldsj ksdqf mklsdflqms" 
le découpage en mot étant défini par "suite de lettres" ou une regex adaptée.

Puis il faut pouvoir préciser si l'on veux une évaluation par index ou par valeur.
Ton exemple avec les pronoms est très bien il pourrait être fait par valeur en vérifiant que les mots sélectionnés sont dans la liste.

mais je suppose que tu a d'autres préoccupations ?

**Comment by esandier** [comment]
Tout à fait d'accord avec les accolades, et une variante qui découpe avec comme séparateur l'espace. La regex, ça m'a l'air compliqué, on verra bien à l'usage s'il y a besoin de plus de flexibilité. 

D'accord aussi pour que l'évaluation puisse être par index ou valeur.

**Comment by nimdanor** [comment]
La regexp c'est asser simple et cela permet de gérer les espaces et la ponctuation comme comportement par défaut. 
Enfin cela permet de traiter des cas spéciaux et de toute façon il y a le système d'héritage pour cacher tout cela sous le tapis.

**Comment by mciissee** [comment]
Donc si je comprends bien pour ce composant, je dois mettre en place un découpage par regex, par espace, par accolade et une sélection libre?

Pour l'évaluation par indice ça serait possible pour tous les modes de découpage que j'ai spécifié sauf le découpage parr accolade

**Comment by ddoyen** [comment]
Ma vision, c'était de rester le plus simple possible côté Angular : on fournit le texte découpé en unités sélectionnables (par des accolades) et ça renvoie l'indice des unités sélectionnées.

Pour les découpages automatiques et l'évaluation, on gère ça avec des méthodes dans la classe Python associée au composant.

**Comment by mciissee** [comment]
Les défauts du découpage par accolade c’est qu’il faut le faire à la main et que les unités sélectionnables sont clairement visibles par l’étudiant s’il inspecte la page ça lui donne des indices sur ce qu’il peut sélectionner et il est avantagé sauf si la quasi-totalité du texte est sélectionnable.

Si ce comportement vous va j’implémente uniquement ce mode.

**Comment by ddoyen** [comment]
En fait, je ne parlais que du mode `word` (qu'il faudrait renommer d'ailleurs). Le mode `free` de sélection libre me semble intéressant aussi.

Le découpage ne sera fera pas vraiment à la main : il sera automatisé dans la classe Python.

Je vais détailler tout ce que je propose comme modif du côté Angular. Ce sera plus clair pour discuter.

**Comment by nimdanor** [comment]
L'idée du découpage par {} c'est que l'on sélectionne tout le mot d'un coup. Si il n'y a pas d'accolades c'est une sélection au caractère.

**Comment by ddoyen** [comment]
Non, on est obligé à mon avis de distinguer deux modes. Et c'est aussi plus intuitif pour l'utilisateur de ne pas mélanger les deux modes.

Dans le mode `units` : on sélectionne des unités du textes par des clics; potentiellement, certaines partie du texte ne sont pas sélectionnables (la ponctuation par exemple). Par ailleurs, le texte peut avoir une mise en forme HTML (alinéas, retour à la ligne) car il suffit de ne pas les mettre entre accolades.

Dans le mode `free` : on sélectionne un ensemble de caractères contigus comme dans un traitement de texte; on déselectionne en cliquant sur un ensemble sélectionné. Ce serait bien aussi que ce mode-là soit compatible avec une mise en forme HTML minimale. Des idées ?

**Comment by ddoyen** [comment]
D'ailleurs, ces histoires de mise en forme pose déjà un problème. Dans le mode `free`, si on rentre une chaîne multilignes (avec `==`) dans  `text`, les sauts de ligne ne sont pas affichés mais les caractères `\n` apparaissent dans la sélection.

**Comment by ddoyen** [comment]
Pour résumer, voilà ce que je propose pour les propriétés (Angular) du composant.

* On garde deux modes. On renomme le mode `word` (je propose `units` mais si quelqu'un a une meilleure idée...)
* On supprime la propriété `separator`.
* On ajoute une propriété `single` (un booléen qui indique si on peut faire une sélection multiple ou non).
* On change la sémantique de `text` avec la convention des accolades.

* Fonctionnement du mode `units`.
Les parties de `text` entre accolades sont transformées en unités sélectionnables. Les autres parties ne sont pas sélectionnables et sont insérées sans modification dans le code HTML (ce qui permet notamment d'inclure des balises HTML). Quand on clique sur une unité sélectionnable, celle-ci est sélectionnée dans sa totalité. Si `single` vaut `true`, tout nouveau clic supprime l'ancienne sélection.

* Fonctionnement du mode `free`.
Chaque caractère des parties de `text` entre accolades sont transformées en unités sélectionnables. Les autres parties ne sont pas sélectionnables et sont insérées sans modification dans le code HTML (ce qui permet notamment d'inclure des balises HTML). On sélectionne les unités en faisant glisser le curseur de sélection comme dans une sélection de texte usuelle. Si `single` vaut `true`, toute nouvelle sélection supprime l'ancienne sélection.

Quelques points de détail. 
* Si on utilise l'accolade comme délimiteur des unités sélectionnables, il faudrait pouvoir l'échapper quand on veut faire apparaître une accolade dans le texte. Cela dit, l'accolade n'est pas un symbole typographique très courant donc ça peut être laissé de côté dans un premier temps.
* Il y a le problème des caractères de contrôle (du genre `\n`) qui vont traîner si on entre `text` sous forme de chaîne multilignes. Soit on dit à l'utilisateur de ne pas rentrer `text` sous cette forme, soit on inclut une suppression des caractères de contrôle quelque part.

**Comment by mciissee** [comment]
https://premierlangage.github.io/platon-front/components/forms/wc-text-select
