### ISSUE TITLE
[WEBCOMPONENT] CodeViewer

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/platon-front#57]
**Selector**
wc-code-viewer

**Goal**
Render code block with syntax highlighting. Enable easy way to copy paste code from exercise texts for users.
The two main uses of this component is :
* display some code to the student explicating a problem or question (text of exercises)
* display some code or behavior (a rendering in Unix terminal for example) during some feedback

**Properties (excluding the default properties cid, selector, debug...)**
| property | description |
|----------|------------|
| `code: string` | code to render  |
| `language: string` | language to use for syntax highlighting  |

**Controller**
An optional python class attached to the component instance.

**Dependencies**
Optional list of javascript or python (for grader) libraries used by the component.

**Example**
Optional link to an exercise that reproduce the behavior of the component.

* This component is a new one, but there already exist deployed exercises what will benefit form this components like the méga feedback of : [learn to doctest factorial](https://pl.u-pem.fr/filebrowser/demo/21603/)
* The terminal style display here is for fun but should be replace by code-viewer in some shell : [comptage dans Germinal](https://pl.u-pem.fr/filebrowser/demo/21967/) (please answer badly or wrongly to see the terminal fun display....)
* This example generated random simple code in C and ask the user to guess the value of a variable at then end : [random arithmetic instruction](https://pl.u-pem.fr/filebrowser/demo/26677/)

**Additional Info**
Add any other context, schemas or screenshots about the component request here.

**Comment by nimdanor** [comment]
I would like a syntaxe like for latex or with tripe back quote.
Something very light and not a a webcomponant for the enduser.

**Comment by mciissee** [comment]
https://premierlangage.github.io/platon-front/components/widgets/wc-code-viewer
