### ISSUE TITLE
[BUG] input text multiline

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/platon-front#59]
**Reproduction**
if the multiline option is used the inputbox.value is not changed 

**Expected Behavior**
the entered value is suppose to be in the inputbox.value field.

**Actual Behavior**
nothing in the inputbox.value variable
**Environment**
  Firefox and chrome

see file /AAAA/BUG/bugrepport1.pl

**Comment by mciissee** [comment]
This bug is not related to the new version of the component
