### ISSUE TITLE
[WEBCOMPONENT] Navigateur

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/platon-front#60]
**Selector**
c-sheet-navigator 
c-navigator
**Goal**
This component is a component associated with a list of ressources [ activities or exercices]. 

Provides a way for the user to choose the next exercice or acticvity.

***Features***:

Support a full page mode, only the menu is proposed. 
Support a menu mode, where the curent ressource is running in a part of the screen and a part of the screen is for the menu.
(like the current pltp page).

**Comment by mciissee** [comment]
Web components are designed for the teachers to be used inside exercices (this is what I understand).
What you describe here seems to be a feature to playexo/playactivity this is not really related to the web components

**Comment by nimdanor** [comment]
I know but we need some thing that is tunable inside an activity.

**Comment by mciissee** [comment]
So this should be **fully** described somewhere else (maybe where playexo/playactivity is described)

**Comment by nimdanor** [comment]
This is the problem this should be in platon-front.
Maybe not with the tag webcomponent.
